# docker-compose.yml
version: "3"
services:
  app:
    build: .
    environment:
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
